### PR TITLE
Use @actions/github for rest calls instead of axios

### PR DESCRIPTION
**Pull request by jeremy-daley-kr**
Seems better to use Github's JS packages to do REST calls rather than manually constructing `axios` requests. Plus it fixes potential proxy issues (currently happening with use of `axios`) for organizations using self-hosted runners.

### CODE REVIEW

**Comment by daleyjem** [comment]
@JamesMGreene You seem to have the most contrib in this repo and the deploy-pages one, where I have proxy-related PRs for both. Any chance you can give these a look?

This is the deploy-pages one: https://github.com/actions/deploy-pages/pull/111

**Comment by JamesMGreene** [comment]
@daleyjem The idea seems sound, though it looks like a few more changes might be necessary. I'll try to get this merged today or tomorrow! 👀

**Comment by daleyjem** [comment]
> @daleyjem The idea seems sound, though it looks like a few more changes might be necessary. I'll try to get this merged today or tomorrow! 👀

Thanks @JamesMGreene. Just pushed up the prettier fix.

**Comment by JamesMGreene** [comment]
@jeremy-daley-kr After some tweaks on our side, I've merged this and released it as `v3.0.4` / the latest `v3`. When you get a chance, please confirm that it met your needs for honoring proxies! 🙇🏻 

Thanks again for the PR! 💝

**Comment by daleyjem** [comment]
@JamesMGreene Appears to have worked! Thanks! FWIW... I added another comment on the deploy-pages PR

**Pull request merged**
