### PR TITLE
Make "Get Pages failed" error message more helpful

### PR DESCRIPTION
**Pull request by WofWca**
I was setting up gh-pages deployment as a GitHub action from the very beginning, and the error was confusing.

### CODE REVIEW

**Comment by JamesMGreene** [comment]
👋🏻 Just wanted to drop a quick note to say that I see your PR, and I appreciate it and its intent. 🙇🏻 

That said, I do want to hold off on it until I get a chance to test this experience more thoroughly, as I'm a bit confused as to the specific configuration that must've been in place to trigger this error.

Did you perhaps run the workflow before enabling Pages at the repository level? 🤔

**Comment by WofWca** [comment]
> Did you perhaps run the workflow before enabling Pages at the repository level?

Well, yes. I made a fork of a repo (that didn't have GitHub Pages) and went straight for creating the GitHub action, without doing anything else, without going to settings or deploying the gh-pages branch manually.

**Comment by JamesMGreene** [comment]
@WofWca Gotcha! Thanks for helping me understand the setup. 🙇🏻

**Review by JamesMGreene — APPROVED** [review]

**Comment by JamesMGreene** [comment]
This has been released in the latest version:

```
uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382
uses: actions/configure-pages@v3.0.6
uses: actions/configure-pages@v3
uses: actions/configure-pages@main
```

**Comment by JamesMGreene** [comment]
Thanks again for the PR, @WofWca! That error message will definitely help some folks avoid this confusion in the future. 💝

**Pull request merged**
